### PR TITLE
Added support for SQL 2016 (Fixes #26)

### LINKED ISSUE #26: sql 2016
Hello, are there any plans to support sql 2016? I need to import bacpac and I've modified module to do that, but obviously my modifications won't work for all the cases (but work for bacpac import).

So for anyone wondering the workaround is to allow xdatabase to accept 2016 as sql version and add a switch condition for '2016' (should be equals to 130).

in MSFT_xDatabase.psm1

```powershell
    "2016"
    {
        $majorVersion = 130
    }
```

also you need to add 2016 to all the validate sets around the module (quite a few places to name them, but you'll eventually find all of them, trying to compile mof file).

### PR DESCRIPTION
**Pull request by Sagnad**
This change adds support for 2016 as a SQL Server version number and maps it to major version 130 in the get SQL Server major version functions.  The value 2016 was added to the schema MOFs for xDatabase and xDBPackage.  The unit tests for xDatabase have been moved to Tests\Unit\ as per the DSC Resource Testing Guidelines.

This is to resolve issue #26 where @kwirkykat asked for help.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdatabase/31)

### CODE REVIEW

**Comment by Sagnad** [comment]
Is there an issue with the fix? We're going to have to use an internal fixed module which is an overhead I'd like to avoid.

**Comment by AmarettoSlim** [comment]
What's the deal here, is this getting accepted? It's passed all checks and has no conflicts ... it'd be nice to have this merged.

At this point the resource already needs SQL Server 2017 support :)

**Comment by johlju** [comment]
Wouldn't it be better to change the parameter `$SqlServerVersion`  to be a string value (without a validate set) that takes a string, and that could be 120,130,135,136,140 and then a change wouldn't be require for each version of new SQL Server.
Althought it would be a breaking change, and not quite as good.

**Comment by johlju** [comment]
:lgtm:

@kwirkykat this looks good to me. Can fly over this and merge whenever you have time?

---

Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdatabase/31#-:-L3CTyc12tHWzZn4UN4r:b-1d9oef)*

**Review by kwirkykat — APPROVED** [review]

**Pull request merged**
