### PR TITLE
Adds support for SQL Server 2019, and 64bit DAC and SMO support

### LINKED ISSUE #46: xDatabase: Add DAC support for SQL Server 2018 and 64 bit DacFramework
There is currently no support for SQL Server 2018 and 64 bit:
The following path should be supported: `C:\Program Files\Microsoft SQL Server\150\DAC\bin` to find the DAC.

### PR DESCRIPTION
**Pull request by ShaneSmith-code**
#### Pull Request (PR) description
 - Updated psm1 and mof for MSFT_xDatabase and MSFT_xDBPackage to include sqlversion 2019 as an option
 - Updated Load-DacFx function in MSFT_xDBPackage and in xDatabase_Common to look for 32bit and 64bit Program Files folder for DAC dll. The first match will be the one that is attempted to load
 - Updated Load-SmoAssembly function in xDatabase_Common to look for 32bit and 64bit Program Files folder for DAC dll. The first match will be the one that is attempted to load

#### This Pull Request (PR) fixes the following issues

- Fixes #46

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xdatabase/48)

### CODE REVIEW

**Comment by johlju** [comment]
I re-targeted this PR against the dev-branch. This repo has not been converted yet to the new DSC Community pipeline, that is a requirement to get this change released, but I can take a look at that. 

I will review this PR now.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdatabase/48)* status: all files reviewed, 6 unresolved discussions (waiting on @ShaneSmith-code)

___
*[README.md, line 55 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH-GnYEwtjozVTn0kq:-MFH-GnYEwtjozVTn0kr:b-1fozrs) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/README.md#L55)):*
> ```
> ### 1.10.0.0
> ```

Please remove this section header, it will be created automatically upon release.
___
*[README.md, line 57 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH-Dq598mboS3r_rA3:-MFH-Dq598mboS3r_rA4:bhl49b9) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/README.md#L57)):*
> ```
> * Added support for SQL Server 2019
> ```

Please move this line under the Unreleased section.
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.schema.mof, line 8 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH-6yc-cH1Aj0xbv2n:-MFH-6yc-cH1Aj0xbv2o:bfi5hui) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/DSCResources/MSFT_xDatabase/MSFT_xDatabase.schema.mof#L8)):*
> ```
> ValueMap{"2008-R2","2012","2014","2016","2017"}
> ```

Need to add "2019" to ValueMap as well.
___
*[DSCResources/MSFT_xDBPackage/MSFT_xDBPackage.psm1, line 208 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH0crS97lw5yUVp8uq:-MFH0crS97lw5yUVp8ur:be2di8l) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/DSCResources/MSFT_xDBPackage/MSFT_xDBPackage.psm1#L208)):*
> ```
> "${env:ProgramFiles(x86)})\Microsoft SQL Server\$majorVersion\DAC\bin\Microsoft.SqlServer.Dac.dll"
> ```

Can we add this path to a variable and reuse that in the both locations?
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 207 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH0oSVCCIQk8eVMm5G:-MFH0oSVCCIQk8eVMm5H:be2di8l) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L207)):*
> ```
> "${env:ProgramFiles(x86)})\Microsoft SQL Server\$majorVersion\DAC\bin\Microsoft.SqlServer.Dac.dll"
> ```

Can we add this path to a variable and reuse that in the both locations?
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 230 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH0t6Y4qOXRa0NtMbP:-MFH0t6Y4qOXRa0NtMbQ:bske9k4) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L230)):*
> ```
> "${env:ProgramFiles(x86)}\Microsoft SQL Server\$majorVersion\SDK\Assemblies\Microsoft.SqlServer.Smo.dll"
> ```

Can we add this path to a variable and reuse that in the both locations?

**Comment by johlju** [comment]
@ShaneSmith-code just minor changes. Great work! 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdatabase/48)* status: all files reviewed, 7 unresolved discussions (waiting on @ShaneSmith-code)

___
*[README.md, line 57 at r4](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-MFH3ZtI6O0grc0ozoXQ:-MFH3ZtI6O0grc0ozoXR:b-4ncd2i) ([raw file](https://github.com/dsccommunity/xdatabase/blob/388511676d06cd5f95376c82186bbf3295bf8a21/README.md#L57)):*
> ```
> * Added support for SQL Server 2019
> ```

Please update the entry  to something like this.

```
* Adds support for SQL Server 2019,
* Add support for 64bit DAC and SMO ([issue #46](https://github.com/dsccommunity/xDatabase/issues/46)).
```

**Comment by johlju** [comment]
@ShaneSmith-code I have PR #49 pending that will convert this repository to the new CI/CD pipeline. Once your PR is merged I will merge the new pipeline PR. After that we can release anew version of the module. 🙂

**Comment by ShaneSmith-code** [comment]
I made the changes recommended in MSFT_xDatabase/MSFT_xDatabase.schema.mof and README.md. I would have to think about how to set up a variable that would be shared across multiple resource blocks. Not sure if it would be worth it for now, but I can give it some thought.

**Comment by johlju** [comment]
I meant one variable in each resources that set the path string so we don't need to duplicate the string. Reusing over multiple resources would be over complicated. 🙂  Sorry for the misunderstanding.

**Comment by ShaneSmith-code** [comment]
Updated MSFT_xDBPackage.psm1 and xDatabase_Common.psm1 with a variable for the portion of the pass that is common.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdatabase/48#-:-MF_CTRe3gYTVVasLNVx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@ShaneSmith-code Thank you for this! I will get the new pipeline in and I will make sure to get a new release out.

**Pull request merged**
