### PR TITLE
If DB exist with DACPAC we will check version in Test

### LINKED ISSUE #41: Test returns false when deploying DB with a DACPAC
If you deploy a database with a DACPAC Test-DSCConfiguration will still fail even after the database was created.

### PR DESCRIPTION
**Pull request by mcollera**
Fixes #41 

This change is [Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)

### CODE REVIEW

**Comment by mcollera** [comment]
This PR fixes #41 Bug

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: all files reviewed, 9 unresolved discussions (waiting on @mcollera)

*[a discussion](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDUgc00qEImmz74tvF:-LJDUgc00qEImmz74tvG:b-6bt7c2) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

---
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDW273-xxRrLXme8Tr:-LJDW273-xxRrLXme8Ts:b-a9a3x7) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
> ```PowerShell
>         else
>         {
>             $deployedVerison = Get-DacPacDeployedVersion -connectionString $ConnectionString -DbName $DatabaseName
> ```

`-ConnectionString'. We should use PascalCase on the named parameters.
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWBh3-3pCQ-dpbpJY:-LJDWBh3-3pCQ-dpbpJZ:btd241v) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
> ```
> $deployedVerison
> ```

` $deployedVersion` -type in 'Version'.
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWRneEpsVCLKHNhPx:-LJDWRneEpsVCLKHNhPy:bl4l1jo) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
> ```PowerShell
>         else
>         {
>             $deployedVerison = Get-DacPacDeployedVersion -connectionString $ConnectionString -DbName $DatabaseName
> ```

We should only do this check when the parameter `$DacPacApplicationVersion` is assigned in the configuration? 
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 39 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWv868iAaNo-Vx3gp:-LJDWv87-MkTdE46mCLY:brfgydz) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L39)):*
> ```PowerShell
>                    [string]$dacpacPath, [string]$dacpacApplicationName, [string]$dacpacApplicationVersion)
> {
>     $defaultDacPacApplicationVersion = "1.0.0.0"
> ```

THis row can move to an else-block in the previous if-block? Then we don't have to set the variable twice.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 139 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDUwXK9l-E-qj9tf-1:-LJDUwXK9l-E-qj9tf-2:b-y32ph7) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L139)):*
> ```PowerShell
> }
> 
> function Get-DacPacDeployedVersion([string]$connectionString, [string]$DbName)
> ```

We should use the correct format from parameters. I know you followed the style of the other functions, but let's start fix to the correct style so we are one step closer. :)

https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 139 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDX_CD8EkzkexHVYJq:-LJDX_CD8EkzkexHVYJr:b-jrz705) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L139)):*
> ```PowerShell
> }
> 
> function Get-DacPacDeployedVersion([string]$connectionString, [string]$DbName)
> ```

Would you mind doing at least a unit test for this helper function? See the helper function part of the unit test template https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1#L156-L164
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 141 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDVFAC8lpB9mAgMsMc:-LJDVFAD-jG_jTFi0X6D:babjtw2) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L141)):*
> ```
> system.data
> ```

System.Data (upper 'S' and 'D')
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 144 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDVi2K8oWxrO84FZTb:-LJDVi2K8oWxrO84FZTc:b-mkfpq7) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L144)):*
> ```
> sqlConnection
> ```

`-SqlConnection'. Lets use PascalCase on the named parameters here even if the function doesn't follow style guideline yet.

**Review by mcollera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @johlju and @mcollera)

*[a discussion](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDUgc00qEImmz74tvF:-LJE2TygDr_gLJOY5USe:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```
</blockquote></details>

Done.

---
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDW273-xxRrLXme8Tr:-LJDyCqEC3AT2wtKQErQ:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`-ConnectionString'. We should use PascalCase on the named parameters.
</blockquote></details>

Done.
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWBh3-3pCQ-dpbpJY:-LJDyDww0gteaZGXp10i:b-9p5u8t) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $deployedVerison
> ```

` $deployedVersion` -type in 'Version'.
</blockquote></details>

I don't understand this comment? are you saying you want me to convert these to type [version] before i compare?
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWRneEpsVCLKHNhPx:-LJDyWKQ0WJX3oF4YGEv:b-9febts) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should only do this check when the parameter `$DacPacApplicationVersion` is assigned in the configuration? 
</blockquote></details>

If $DacPacApplicationVersion is not provided it will just be $null. So it will still return false. the way the original code was written was if DacPacPath was supplied and DbExist then return false. so we will still get the same result. I can do a check first but it would be extra lines of code.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 39 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWv868iAaNo-Vx3gp:-LJDz0Il5eEKHA-731rn:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L39)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

THis row can move to an else-block in the previous if-block? Then we don't have to set the variable twice.
</blockquote></details>

Done.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 139 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDUwXK9l-E-qj9tf-1:-LJDyyh4CpdqxVxN4sN0:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L139)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use the correct format from parameters. I know you followed the style of the other functions, but let's start fix to the correct style so we are one step closer. :)

https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
</blockquote></details>

Done.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 139 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDX_CD8EkzkexHVYJq:-LJE18F75V6gNPX2VbDY:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L139)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would you mind doing at least a unit test for this helper function? See the helper function part of the unit test template https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1#L156-L164
</blockquote></details>

Done.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 141 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDVFAC8lpB9mAgMsMc:-LJDyzSY3yPIdyG-TDK8:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L141)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> system.data
> ```

System.Data (upper 'S' and 'D')
</blockquote></details>

Done.
___
*[DSCResources/xDatabase_Common/xDatabase_Common.psm1, line 144 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDVi2K8oWxrO84FZTb:-LJDz-KV8Q8Cb34V0pU4:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/xDatabase_Common/xDatabase_Common.psm1#L144)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> sqlConnection
> ```

`-SqlConnection'. Lets use PascalCase on the named parameters here even if the function doesn't follow style guideline yet.
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @johlju and @mcollera)

___
*[README.md, line 51 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJI9K1fBptkkbBPrrH8:-LJI9K1gDqkvL0O-ftky:b5jo8yi) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/README.md#L51)):*
> ```
> Test-TargetItem
> ```

Test-TargetResource
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWBh3-3pCQ-dpbpJY:-LJI9Vrt2iEwRCce3uaz:bkkoisq) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, mcollera wrote…</i></summary><blockquote>

I don't understand this comment? are you saying you want me to convert these to type [version] before i compare?
</blockquote></details>

My bad. Looks like I was typing to fast there. It meant to say " - typo in 'Version'". There is a spelling error in the word 'Version' :slightly_smiling_face: 
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWRneEpsVCLKHNhPx:-LJIADyU7fNCHLPg8avP:b-rho96n) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, mcollera wrote…</i></summary><blockquote>

If $DacPacApplicationVersion is not provided it will just be $null. So it will still return false. the way the original code was written was if DacPacPath was supplied and DbExist then return false. so we will still get the same result. I can do a check first but it would be extra lines of code.
</blockquote></details>

If the parameter `$DacPacApplicationVersion` is not provided, it's probably faster to evaluate an `if` than get the deployed version and the compare it to $null. But if you like you can leave it as-is.
___
*[Tests/Unit/MSFT_xDatabase.Tests.ps1, line 49 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJIBYPA72bigm9ht9Fk:-LJIBYPA72bigm9ht9Fl:b-w8d0ur) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/Tests/Unit/MSFT_xDatabase.Tests.ps1#L49)):*
> ```PowerShell
> }
> 
> Describe 'xDatabase_Common\Get-DacPacDeployedVersion' -Tag 'Helper' {
> ```

Can you please move this helper function unit tests to a separate file, e.g `xDatabase_Common.Tests.ps1`. We should also use the the unit test template here
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1. The header in the unit test template need to be modified slightly since we are not loading a resource.
___
*[Tests/Unit/MSFT_xDatabase.Tests.ps1, line 51 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJICq-c2QHvJzEyqqq0:-LJICq-c2QHvJzEyqqq1:bguaq8q) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/Tests/Unit/MSFT_xDatabase.Tests.ps1#L51)):*
> ```PowerShell
> Describe 'xDatabase_Common\Get-DacPacDeployedVersion' -Tag 'Helper' {
>   Copy-Item -Path "$here\$common" -Destination TestDrive:\helper.ps1
>   . TestDrive:\helper.ps1
> ```

We should not dot-source, but rather use `Import-Module` and `InModuleScope`-block, see unit test template in previous comment.

**Review by mcollera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @johlju)

___
*[README.md, line 51 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJI9K1fBptkkbBPrrH8:-LJJ3CH96lZ47_OQAMrM:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/README.md#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Test-TargetItem
> ```

Test-TargetResource
</blockquote></details>

Done.
___
*[DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1, line 209 at r1](https://reviewable.io/reviews/powershell/xdatabase/42#-LJDWBh3-3pCQ-dpbpJY:-LJJ34W85EVEBya5ym9J:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/204a9dfc3d5c2fea8252302032e21eade7d0d940/DSCResources/MSFT_xDatabase/MSFT_xDatabase.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

My bad. Looks like I was typing to fast there. It meant to say " - typo in 'Version'". There is a spelling error in the word 'Version' :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[Tests/Unit/MSFT_xDatabase.Tests.ps1, line 49 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJIBYPA72bigm9ht9Fk:-LJJ6Ku7EV_3tIP62q7U:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/Tests/Unit/MSFT_xDatabase.Tests.ps1#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can you please move this helper function unit tests to a separate file, e.g `xDatabase_Common.Tests.ps1`. We should also use the the unit test template here
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1. The header in the unit test template need to be modified slightly since we are not loading a resource.
</blockquote></details>

Done.
___
*[Tests/Unit/MSFT_xDatabase.Tests.ps1, line 51 at r2](https://reviewable.io/reviews/powershell/xdatabase/42#-LJICq-c2QHvJzEyqqq0:-LJJ6Kho8MtSX8BrN3nC:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/2b3c4b935294ec2b2d222e42861dd73632c47bf9/Tests/Unit/MSFT_xDatabase.Tests.ps1#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should not dot-source, but rather use `Import-Module` and `InModuleScope`-block, see unit test template in previous comment.
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
Just one minor comment left.  Then this is good to go I think. :smiley: 

> Reviewed 1 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42#-:-LJNgFqXDVKb0UOaL7Aw:b-w32s5n)* status: all files reviewed, 1 unresolved discussion (waiting on @mcollera)

___
*[Tests/Unit/xDatabase_Common.Tests.ps1, line 16 at r3](https://reviewable.io/reviews/powershell/xdatabase/42#-LJNfZ05B4ICoP10WoM6:-LJNfZ05B4ICoP10WoM7:b-216tm1) ([raw file](https://github.com/powershell/xdatabase/blob/0e2c9ae4606e8f06a1a3b1f61ce9ec3356d131eb/Tests/Unit/xDatabase_Common.Tests.ps1#L16)):*
> ```
> -MockWith {}
> ```

We can remove this since the parameter is only necessary when there is a code-block.

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: all files reviewed, 2 unresolved discussions (waiting on @mcollera)

___
*[Tests/Unit/xDatabase_Common.Tests.ps1, line 29 at r3](https://reviewable.io/reviews/powershell/xdatabase/42#-LJNgMyf6-WDIdJy4_bu:-LJNgMyf6-WDIdJy4_bv:bysxuen) ([raw file](https://github.com/powershell/xdatabase/blob/0e2c9ae4606e8f06a1a3b1f61ce9ec3356d131eb/Tests/Unit/xDatabase_Common.Tests.ps1#L29)):*
> ```PowerShell
>         }
>       }    
> }
> ```

Please add a single new line at the end of the file. 

*If you use VSCode you can change a setting so the editor does this automatically on save.*

**Review by mcollera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[Tests/Unit/xDatabase_Common.Tests.ps1, line 16 at r3](https://reviewable.io/reviews/powershell/xdatabase/42#-LJNfZ05B4ICoP10WoM6:-LJOr0WgAfLRchs6CzWW:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/0e2c9ae4606e8f06a1a3b1f61ce9ec3356d131eb/Tests/Unit/xDatabase_Common.Tests.ps1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -MockWith {}
> ```

We can remove this since the parameter is only necessary when there is a code-block.
</blockquote></details>

Done.
___
*[Tests/Unit/xDatabase_Common.Tests.ps1, line 29 at r3](https://reviewable.io/reviews/powershell/xdatabase/42#-LJNgMyf6-WDIdJy4_bu:-LJOr4Ks7j6HvZS87j2K:b-896fix) ([raw file](https://github.com/powershell/xdatabase/blob/0e2c9ae4606e8f06a1a3b1f61ce9ec3356d131eb/Tests/Unit/xDatabase_Common.Tests.ps1#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a single new line at the end of the file. 

*If you use VSCode you can change a setting so the editor does this automatically on save.*
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/powershell/xdatabase/42#-:-LJSvpw47non8xFh9JtL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
